#!/usr/bin/env bash
# patchServerMemory.sh
# Compiles and deploys two Java-level server memory patches for PZ Build 42.19.
#
# Patch B - chunkStore pool cap  (IsoChunk.java)
#   removeFromWorld() caps the IsoChunkMap.chunkStore recycling pool at 256
#   objects.  Prevents unbounded IsoChunk accumulation during long sessions.
#
# Patch D - ServerLOS early suspend  (ServerMap.java)
#   postupdate() suspends the LOS background thread before the update loop
#   (not lazily inside it), preventing pathfind/physics work enqueued by
#   cell.update() from racing with Unload() calls later in the same frame.
#
# Prerequisites:
#   The patched source files must exist in src/ next to this script.
#   Generate them on a Windows machine by running patchServerMemory.ps1, then
#   commit the resulting src/ files and push before running this script.
#
# Usage:
#   ./patchServerMemory.sh [--pz-dir PATH] [--dry-run] [--revert]
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PATCH_NAME="Server Memory Optimizations - Patches B, D, E"

# Source files (generated by patchServerMemory.ps1 and committed to the repo)
SRC_GAMESERVER="$SCRIPT_DIR/src/zombie/network/GameServer.java"
SRC_ISOCHUNK="$SCRIPT_DIR/src/zombie/iso/IsoChunk.java"
SRC_SERVERMAP="$SCRIPT_DIR/src/zombie/network/ServerMap.java"

# --- Argument parsing ---
PZ_DIR="/opt/pzserver"
DRY_RUN=false
REVERT=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --pz-dir)    PZ_DIR="$2";  shift 2 ;;
        --dry-run)   DRY_RUN=true; shift   ;;
        --revert|-r) REVERT=true;  shift   ;;
        *)
            echo "Unknown option: $1" >&2
            echo "Usage: $0 [--pz-dir PATH] [--dry-run] [--revert]" >&2
            exit 1
            ;;
    esac
done

# Auto-detect JAR location (Linux server: java/ subdir; Windows: PZ root)
if [[ -f "$PZ_DIR/java/projectzomboid.jar" ]]; then
    JAR_FILE="$PZ_DIR/java/projectzomboid.jar"
    DEPLOY_BASE="$PZ_DIR/java"
else
    JAR_FILE="$PZ_DIR/projectzomboid.jar"
    DEPLOY_BASE="$PZ_DIR"
fi
DEPLOY_NET="$DEPLOY_BASE/zombie/network"
DEPLOY_ISO="$DEPLOY_BASE/zombie/iso"
BACKUP_DIR="$SCRIPT_DIR/backups/ServerMemory"
WORK_DIR="/tmp/pzpatch_servermemory"
OUTPUT_DIR="$WORK_DIR/classes"

REQUIRED_MAJOR=25

echo ""
echo "=== PZ Classpath Override Patch ==="
echo "=== $PATCH_NAME ==="
echo ""

# ---------------------------------------------------------------------------
# Revert mode
# ---------------------------------------------------------------------------
if [[ "$REVERT" == "true" ]]; then
    echo "[*] Reverting patch..."
    reverted=false

    declare -a ALL_CLASSES=(
        "$DEPLOY_NET/GameServer.class"
        "$DEPLOY_NET/GameServer\$1.class"
        "$DEPLOY_NET/GameServer\$2.class"
        "$DEPLOY_NET/GameServer\$CCFilter.class"
        "$DEPLOY_NET/GameServer\$DelayedConnection.class"
        "$DEPLOY_NET/GameServer\$MapRemotePlayerVisibility.class"
        "$DEPLOY_NET/GameServer\$s_performance.class"
        "$DEPLOY_ISO/IsoChunk.class"
        "$DEPLOY_ISO/IsoChunk\$1.class"
        "$DEPLOY_ISO/IsoChunk\$ChunkGetter.class"
        "$DEPLOY_ISO/IsoChunk\$ChunkLock.class"
        "$DEPLOY_ISO/IsoChunk\$JobType.class"
        "$DEPLOY_ISO/IsoChunk\$PhysicsShapes.class"
        "$DEPLOY_ISO/IsoChunk\$SanityCheck.class"
        "$DEPLOY_NET/ServerMap.class"
        "$DEPLOY_NET/ServerMap\$DistToCellComparator.class"
        "$DEPLOY_NET/ServerMap\$EThreadCommand.class"
        "$DEPLOY_NET/ServerMap\$ServerCell.class"
        "$DEPLOY_NET/ServerMap\$WorkerThread.class"
        "$DEPLOY_NET/ServerMap\$WorkerThreadCommand.class"
    )

    for f in "${ALL_CLASSES[@]}"; do
        if [[ -f "$f" ]]; then
            rm -f "$f"
            echo "    Removed: $f"
            reverted=true
        fi
    done

    if [[ "$reverted" == "true" ]]; then
        echo ""
        echo "=== Patch reverted. JAR originals restored on next server start. ==="
    else
        echo "    No patch files found to remove."
    fi
    exit 0
fi

# ---------------------------------------------------------------------------
# Validate prerequisites
# ---------------------------------------------------------------------------
if [[ ! -f "$JAR_FILE" ]]; then
    echo "ERROR: projectzomboid.jar not found at $JAR_FILE" >&2
    echo "       Set --pz-dir to your Project Zomboid server directory." >&2
    exit 1
fi

missing_sources=false
for src in "$SRC_GAMESERVER" "$SRC_ISOCHUNK" "$SRC_SERVERMAP"; do
    if [[ ! -f "$src" ]]; then
        echo "ERROR: Patched source not found: $src" >&2
        missing_sources=true
    fi
done
if [[ "$missing_sources" == "true" ]]; then
    echo "" >&2
    echo "  The patched Java source files are missing." >&2
    echo "  Run patchServerMemory.ps1 on a Windows machine that has the" >&2
    echo "  ZomboidDecompiler output, then commit and push the generated" >&2
    echo "  src/ files before running this script." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Find javac
# ---------------------------------------------------------------------------
JAVAC=""

if command -v javac &>/dev/null; then
    ver=$(javac -version 2>&1 | grep -oP '\d+' | head -1 || echo 0)
    if (( ver >= REQUIRED_MAJOR )); then
        JAVAC=$(command -v javac)
    fi
fi

if [[ -z "$JAVAC" ]]; then
    JAVAC="/usr/lib/jvm/java-${REQUIRED_MAJOR}-openjdk-amd64/bin/javac"
fi

if [[ ! -x "$JAVAC" ]]; then
    echo "ERROR: javac >= $REQUIRED_MAJOR not found." >&2
    echo "       Install: apt install openjdk-${REQUIRED_MAJOR}-jdk-headless" >&2
    exit 1
fi

echo "[*] PZ dir:    $PZ_DIR"
echo "[*] JAR:       $JAR_FILE"
echo "[*] Deploy:    $DEPLOY_NET  |  $DEPLOY_ISO"
echo "[*] javac:     $JAVAC ($("$JAVAC" -version 2>&1 | head -1))"
echo ""

# ---------------------------------------------------------------------------
# Backup originals from JAR
# ---------------------------------------------------------------------------
backup_class() {
    local label="$1"
    local jar_entry="$2"
    local backup_subdir="$BACKUP_DIR/$label"
    local backup_file="$backup_subdir/$(basename "$jar_entry").original"

    if [[ -f "$backup_file" ]]; then
        return
    fi

    mkdir -p "$backup_subdir"
    local extract_tmp="$SCRIPT_DIR/tmp-extract-$label"
    rm -rf "$extract_tmp"
    mkdir -p "$extract_tmp"
    pushd "$extract_tmp" > /dev/null
    jar xf "$JAR_FILE" "$jar_entry" 2>/dev/null || true
    if [[ -f "$extract_tmp/$jar_entry" ]]; then
        cp "$extract_tmp/$jar_entry" "$backup_file"
        echo "    Backed up: $(basename "$jar_entry")"
    fi
    popd > /dev/null
    rm -rf "$extract_tmp"
}

echo "[*] Backing up original classes from JAR..."
for entry in \
    "zombie/network/GameServer.class" \
    'zombie/network/GameServer$1.class' \
    'zombie/network/GameServer$2.class' \
    'zombie/network/GameServer$CCFilter.class' \
    'zombie/network/GameServer$DelayedConnection.class' \
    'zombie/network/GameServer$MapRemotePlayerVisibility.class' \
    'zombie/network/GameServer$s_performance.class'; do
    backup_class "GameServer" "$entry"
done

for entry in \
    "zombie/iso/IsoChunk.class" \
    'zombie/iso/IsoChunk$1.class' \
    'zombie/iso/IsoChunk$ChunkGetter.class' \
    'zombie/iso/IsoChunk$ChunkLock.class' \
    'zombie/iso/IsoChunk$JobType.class' \
    'zombie/iso/IsoChunk$PhysicsShapes.class' \
    'zombie/iso/IsoChunk$SanityCheck.class'; do
    backup_class "IsoChunk" "$entry"
done

for entry in \
    "zombie/network/ServerMap.class" \
    'zombie/network/ServerMap$DistToCellComparator.class' \
    'zombie/network/ServerMap$EThreadCommand.class' \
    'zombie/network/ServerMap$ServerCell.class' \
    'zombie/network/ServerMap$WorkerThread.class' \
    'zombie/network/ServerMap$WorkerThreadCommand.class'; do
    backup_class "ServerMap" "$entry"
done

# ---------------------------------------------------------------------------
# Compile
# ---------------------------------------------------------------------------
echo ""
echo "[*] Compiling patched sources..."
rm -rf "$WORK_DIR"
mkdir -p "$OUTPUT_DIR"

# Stage sources in a tree matching their package paths
mkdir -p "$WORK_DIR/src/zombie/network"
mkdir -p "$WORK_DIR/src/zombie/iso"
cp "$SRC_GAMESERVER" "$WORK_DIR/src/zombie/network/GameServer.java"
cp "$SRC_ISOCHUNK"   "$WORK_DIR/src/zombie/iso/IsoChunk.java"
cp "$SRC_SERVERMAP"  "$WORK_DIR/src/zombie/network/ServerMap.java"

"$JAVAC" --release 25 \
    -cp "$JAR_FILE" \
    -d  "$OUTPUT_DIR" \
    -encoding UTF-8 \
    -nowarn \
    "$WORK_DIR/src/zombie/network/GameServer.java" \
    "$WORK_DIR/src/zombie/iso/IsoChunk.java" \
    "$WORK_DIR/src/zombie/network/ServerMap.java"

echo "    Compiled successfully."

# ---------------------------------------------------------------------------
# Deploy
# ---------------------------------------------------------------------------
echo ""
if [[ "$DRY_RUN" == "true" ]]; then
    echo "[*] DRY RUN: Would deploy to:"
    echo "    $DEPLOY_NET"
    echo "    $DEPLOY_ISO"
    find "$OUTPUT_DIR" -name "GameServer*.class" -o -name "IsoChunk*.class" -o -name "ServerMap*.class" | \
        while read -r f; do echo "    $(basename "$f")"; done
else
    echo "[*] Deploying..."
    mkdir -p "$DEPLOY_NET" "$DEPLOY_ISO"
    ts=$(date +%Y%m%d_%H%M%S)

    # GameServer classes
    while IFS= read -r -d '' f; do
        dest="$DEPLOY_NET/$(basename "$f")"
        if [[ -f "$dest" ]]; then
            cp "$dest" "$BACKUP_DIR/GameServer/$(basename "$f").prev_$ts" 2>/dev/null || true
        fi
        cp "$f" "$dest"
        echo "    Deployed: zombie/network/$(basename "$f")"
    done < <(find "$OUTPUT_DIR/zombie/network" -maxdepth 1 \
        \( -name "GameServer.class" -o -name 'GameServer$*.class' \) -print0)

    # IsoChunk classes
    while IFS= read -r -d '' f; do
        dest="$DEPLOY_ISO/$(basename "$f")"
        if [[ -f "$dest" ]]; then
            cp "$dest" "$BACKUP_DIR/IsoChunk/$(basename "$f").prev_$ts" 2>/dev/null || true
        fi
        cp "$f" "$dest"
        echo "    Deployed: zombie/iso/$(basename "$f")"
    done < <(find "$OUTPUT_DIR/zombie/iso" -maxdepth 1 \
        \( -name "IsoChunk.class" -o -name 'IsoChunk$*.class' \) -print0)

    # ServerMap classes
    while IFS= read -r -d '' f; do
        dest="$DEPLOY_NET/$(basename "$f")"
        if [[ -f "$dest" ]]; then
            cp "$dest" "$BACKUP_DIR/ServerMap/$(basename "$f").prev_$ts" 2>/dev/null || true
        fi
        cp "$f" "$dest"
        echo "    Deployed: zombie/network/$(basename "$f")"
    done < <(find "$OUTPUT_DIR/zombie/network" -maxdepth 1 \
        \( -name "ServerMap.class" -o -name 'ServerMap$*.class' \) -print0)
fi

# Cleanup
rm -rf "$WORK_DIR"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "=== Done ==="
echo ""
echo "Patch deployed: $PATCH_NAME"
echo ""
echo "How it works:"
echo "  PZ classpath has '.' before 'projectzomboid.jar', so the loose .class"
echo "  files in '$PZ_DIR/zombie/' take precedence over JAR entries."
echo ""
echo "To revert:"
echo "  ./patchServerMemory.sh --revert"
echo ""
